//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ADIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ADIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Finish" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}ColorsType" minOccurs="0"/>
 *         &lt;element name="Top" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}ColorsType" minOccurs="0"/>
 *         &lt;element name="Interior" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}InteriorsType" minOccurs="0"/>
 *         &lt;element name="Paint" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}ColorsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ADIType", propOrder = {
    "finish",
    "top",
    "interior",
    "paint"
})
public class ADIType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Finish", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected ColorsType finish;
    @XmlElement(name = "Top", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected ColorsType top;
    @XmlElement(name = "Interior", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected InteriorsType interior;
    @XmlElement(name = "Paint", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected ColorsType paint;

    /**
     * Gets the value of the finish property.
     * 
     * @return
     *     possible object is
     *     {@link ColorsType }
     *     
     */
    public ColorsType getFinish() {
        return finish;
    }

    /**
     * Sets the value of the finish property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorsType }
     *     
     */
    public void setFinish(ColorsType value) {
        this.finish = value;
    }

    public boolean isSetFinish() {
        return (this.finish!= null);
    }

    /**
     * Gets the value of the top property.
     * 
     * @return
     *     possible object is
     *     {@link ColorsType }
     *     
     */
    public ColorsType getTop() {
        return top;
    }

    /**
     * Sets the value of the top property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorsType }
     *     
     */
    public void setTop(ColorsType value) {
        this.top = value;
    }

    public boolean isSetTop() {
        return (this.top!= null);
    }

    /**
     * Gets the value of the interior property.
     * 
     * @return
     *     possible object is
     *     {@link InteriorsType }
     *     
     */
    public InteriorsType getInterior() {
        return interior;
    }

    /**
     * Sets the value of the interior property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteriorsType }
     *     
     */
    public void setInterior(InteriorsType value) {
        this.interior = value;
    }

    public boolean isSetInterior() {
        return (this.interior!= null);
    }

    /**
     * Gets the value of the paint property.
     * 
     * @return
     *     possible object is
     *     {@link ColorsType }
     *     
     */
    public ColorsType getPaint() {
        return paint;
    }

    /**
     * Sets the value of the paint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorsType }
     *     
     */
    public void setPaint(ColorsType value) {
        this.paint = value;
    }

    public boolean isSetPaint() {
        return (this.paint!= null);
    }

}
