//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AliveTestAcknowledgementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AliveTestAcknowledgementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceProvider" type="{http://xmldefs.vwgoa.na.vwg/DD/Commons/V2}ServiceProviderType"/>
 *         &lt;element name="ServiceInfo" type="{http://xmldefs.vwgoa.na.vwg/DD/Commons/V2}ServiceInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AliveTestAcknowledgementType", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", propOrder = {
    "serviceProvider",
    "serviceInfo"
})
public class AliveTestAcknowledgementType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ServiceProvider", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected ServiceProviderType serviceProvider;
    @XmlElement(name = "ServiceInfo", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected ServiceInfoType serviceInfo;

    /**
     * Gets the value of the serviceProvider property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceProviderType }
     *     
     */
    public ServiceProviderType getServiceProvider() {
        return serviceProvider;
    }

    /**
     * Sets the value of the serviceProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceProviderType }
     *     
     */
    public void setServiceProvider(ServiceProviderType value) {
        this.serviceProvider = value;
    }

    public boolean isSetServiceProvider() {
        return (this.serviceProvider!= null);
    }

    /**
     * Gets the value of the serviceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceInfoType }
     *     
     */
    public ServiceInfoType getServiceInfo() {
        return serviceInfo;
    }

    /**
     * Sets the value of the serviceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceInfoType }
     *     
     */
    public void setServiceInfo(ServiceInfoType value) {
        this.serviceInfo = value;
    }

    public boolean isSetServiceInfo() {
        return (this.serviceInfo!= null);
    }

}
