//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EngineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EngineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EngineCode" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType" minOccurs="0"/>
 *         &lt;element name="EngineCodeExtension" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EngineType", propOrder = {
    "engineCode",
    "engineCodeExtension"
})
public class EngineType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EngineCode", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected CodeType engineCode;
    @XmlElement(name = "EngineCodeExtension", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected CodeType engineCodeExtension;

    /**
     * Gets the value of the engineCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getEngineCode() {
        return engineCode;
    }

    /**
     * Sets the value of the engineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setEngineCode(CodeType value) {
        this.engineCode = value;
    }

    public boolean isSetEngineCode() {
        return (this.engineCode!= null);
    }

    /**
     * Gets the value of the engineCodeExtension property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getEngineCodeExtension() {
        return engineCodeExtension;
    }

    /**
     * Sets the value of the engineCodeExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setEngineCodeExtension(CodeType value) {
        this.engineCodeExtension = value;
    }

    public boolean isSetEngineCodeExtension() {
        return (this.engineCodeExtension!= null);
    }

}
