//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EquipmentOptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquipmentOptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OptionCode" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType"/>
 *         &lt;element name="EquipmentClass" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType" minOccurs="0"/>
 *         &lt;element name="Family" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}String" minOccurs="0"/>
 *         &lt;element name="Descriptions" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}EquipmentDescriptionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquipmentOptionType", propOrder = {
    "optionCode",
    "equipmentClass",
    "family",
    "descriptions"
})
public class EquipmentOptionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "OptionCode", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle", required = true)
    protected CodeType optionCode;
    @XmlElement(name = "EquipmentClass", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected CodeType equipmentClass;
    @XmlElement(name = "Family", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String family;
    @XmlElement(name = "Descriptions", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected EquipmentDescriptionsType descriptions;

    /**
     * Gets the value of the optionCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getOptionCode() {
        return optionCode;
    }

    /**
     * Sets the value of the optionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setOptionCode(CodeType value) {
        this.optionCode = value;
    }

    public boolean isSetOptionCode() {
        return (this.optionCode!= null);
    }

    /**
     * Gets the value of the equipmentClass property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getEquipmentClass() {
        return equipmentClass;
    }

    /**
     * Sets the value of the equipmentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setEquipmentClass(CodeType value) {
        this.equipmentClass = value;
    }

    public boolean isSetEquipmentClass() {
        return (this.equipmentClass!= null);
    }

    /**
     * Gets the value of the family property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamily() {
        return family;
    }

    /**
     * Sets the value of the family property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamily(String value) {
        this.family = value;
    }

    public boolean isSetFamily() {
        return (this.family!= null);
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentDescriptionsType }
     *     
     */
    public EquipmentDescriptionsType getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentDescriptionsType }
     *     
     */
    public void setDescriptions(EquipmentDescriptionsType value) {
        this.descriptions = value;
    }

    public boolean isSetDescriptions() {
        return (this.descriptions!= null);
    }

}
