//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EquipmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquipmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EquipmentOptions" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}EquipmentOptionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquipmentType", propOrder = {
    "equipmentOptions"
})
public class EquipmentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EquipmentOptions", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected EquipmentOptionsType equipmentOptions;

    /**
     * Gets the value of the equipmentOptions property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentOptionsType }
     *     
     */
    public EquipmentOptionsType getEquipmentOptions() {
        return equipmentOptions;
    }

    /**
     * Sets the value of the equipmentOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentOptionsType }
     *     
     */
    public void setEquipmentOptions(EquipmentOptionsType value) {
        this.equipmentOptions = value;
    }

    public boolean isSetEquipmentOptions() {
        return (this.equipmentOptions!= null);
    }

}
