//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for FaultBasicType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FaultBasicType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FaultSystem" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType"/>
 *         &lt;element name="FaultClass" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType"/>
 *         &lt;element name="FaultCode" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}String"/>
 *         &lt;element name="FaultLevel" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType"/>
 *         &lt;element name="FaultID" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}String" minOccurs="0"/>
 *         &lt;element name="FaultTimestamp" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}String"/>
 *         &lt;element name="FaultDescription" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}TextType"/>
 *         &lt;element name="FaultCodeDetails" type="{http://xmldefs.vwgoa.na.vwg/DD/Commons/V2}FaultCodeDetailType" minOccurs="0"/>
 *         &lt;element name="FaultSystemDetails" type="{http://xmldefs.vwgoa.na.vwg/DD/Commons/V2}FaultSystemDetailType" minOccurs="0"/>
 *         &lt;element name="FaultReason" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FaultBasicType", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", propOrder = {
    "faultSystem",
    "faultClass",
    "faultCode",
    "faultLevel",
    "faultID",
    "faultTimestamp",
    "faultDescription",
    "faultCodeDetails",
    "faultSystemDetails",
    "faultReason"
})
public class FaultBasicType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "FaultSystem", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected CodeType faultSystem;
    @XmlElement(name = "FaultClass", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected CodeType faultClass;
    @XmlElement(name = "FaultCode", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String faultCode;
    @XmlElement(name = "FaultLevel", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected CodeType faultLevel;
    @XmlElement(name = "FaultID", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String faultID;
    @XmlElement(name = "FaultTimestamp", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String faultTimestamp;
    @XmlElement(name = "FaultDescription", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected TextType faultDescription;
    @XmlElement(name = "FaultCodeDetails", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2")
    protected FaultCodeDetailType faultCodeDetails;
    @XmlElement(name = "FaultSystemDetails", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2")
    protected FaultSystemDetailType faultSystemDetails;
    @XmlElement(name = "FaultReason", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String faultReason;

    /**
     * Gets the value of the faultSystem property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getFaultSystem() {
        return faultSystem;
    }

    /**
     * Sets the value of the faultSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setFaultSystem(CodeType value) {
        this.faultSystem = value;
    }

    public boolean isSetFaultSystem() {
        return (this.faultSystem!= null);
    }

    /**
     * Gets the value of the faultClass property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getFaultClass() {
        return faultClass;
    }

    /**
     * Sets the value of the faultClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setFaultClass(CodeType value) {
        this.faultClass = value;
    }

    public boolean isSetFaultClass() {
        return (this.faultClass!= null);
    }

    /**
     * Gets the value of the faultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultCode() {
        return faultCode;
    }

    /**
     * Sets the value of the faultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultCode(String value) {
        this.faultCode = value;
    }

    public boolean isSetFaultCode() {
        return (this.faultCode!= null);
    }

    /**
     * Gets the value of the faultLevel property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getFaultLevel() {
        return faultLevel;
    }

    /**
     * Sets the value of the faultLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setFaultLevel(CodeType value) {
        this.faultLevel = value;
    }

    public boolean isSetFaultLevel() {
        return (this.faultLevel!= null);
    }

    /**
     * Gets the value of the faultID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultID() {
        return faultID;
    }

    /**
     * Sets the value of the faultID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultID(String value) {
        this.faultID = value;
    }

    public boolean isSetFaultID() {
        return (this.faultID!= null);
    }

    /**
     * Gets the value of the faultTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultTimestamp() {
        return faultTimestamp;
    }

    /**
     * Sets the value of the faultTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultTimestamp(String value) {
        this.faultTimestamp = value;
    }

    public boolean isSetFaultTimestamp() {
        return (this.faultTimestamp!= null);
    }

    /**
     * Gets the value of the faultDescription property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getFaultDescription() {
        return faultDescription;
    }

    /**
     * Sets the value of the faultDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setFaultDescription(TextType value) {
        this.faultDescription = value;
    }

    public boolean isSetFaultDescription() {
        return (this.faultDescription!= null);
    }

    /**
     * Gets the value of the faultCodeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link FaultCodeDetailType }
     *     
     */
    public FaultCodeDetailType getFaultCodeDetails() {
        return faultCodeDetails;
    }

    /**
     * Sets the value of the faultCodeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultCodeDetailType }
     *     
     */
    public void setFaultCodeDetails(FaultCodeDetailType value) {
        this.faultCodeDetails = value;
    }

    public boolean isSetFaultCodeDetails() {
        return (this.faultCodeDetails!= null);
    }

    /**
     * Gets the value of the faultSystemDetails property.
     * 
     * @return
     *     possible object is
     *     {@link FaultSystemDetailType }
     *     
     */
    public FaultSystemDetailType getFaultSystemDetails() {
        return faultSystemDetails;
    }

    /**
     * Sets the value of the faultSystemDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultSystemDetailType }
     *     
     */
    public void setFaultSystemDetails(FaultSystemDetailType value) {
        this.faultSystemDetails = value;
    }

    public boolean isSetFaultSystemDetails() {
        return (this.faultSystemDetails!= null);
    }

    /**
     * Gets the value of the faultReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultReason() {
        return faultReason;
    }

    /**
     * Sets the value of the faultReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultReason(String value) {
        this.faultReason = value;
    }

    public boolean isSetFaultReason() {
        return (this.faultReason!= null);
    }

}
