//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FaultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FaultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmldefs.vwgoa.na.vwg/DD/Commons/V2}FaultBasic"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FaultType", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", propOrder = {
    "faultBasic"
})
public class FaultType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "FaultBasic", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected FaultBasicType faultBasic;

    /**
     * Gets the value of the faultBasic property.
     * 
     * @return
     *     possible object is
     *     {@link FaultBasicType }
     *     
     */
    public FaultBasicType getFaultBasic() {
        return faultBasic;
    }

    /**
     * Sets the value of the faultBasic property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultBasicType }
     *     
     */
    public void setFaultBasic(FaultBasicType value) {
        this.faultBasic = value;
    }

    public boolean isSetFaultBasic() {
        return (this.faultBasic!= null);
    }

}
