//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TM" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Q" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PARAM" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="original_value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="url_escaped_value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="js_escaped_value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Context">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RES">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="M" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="NB">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RG" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="START" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="SIZE" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="R" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="U" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="T" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RK" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="S" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LANG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PageMap">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DataObject" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Attribute" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="HAS">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="L" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="C">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="SZ" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="CID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="RT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RHS_COLUMN">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RG">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="START" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="SIZE" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="SN" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="EN" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="VER" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tm",
    "q",
    "param",
    "context",
    "res"
})
@XmlRootElement(name = "GSP", namespace = "")
public class GSP
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TM", required = true)
    protected BigDecimal tm;
    @XmlElement(name = "Q", required = true)
    protected String q;
    @XmlElement(name = "PARAM", required = true)
    protected List<GSP.PARAM> param;
    @XmlElement(name = "Context", required = true)
    protected GSP.Context context;
    @XmlElement(name = "RES", required = true)
    protected GSP.RES res;
    @XmlAttribute(name = "VER")
    protected BigDecimal ver;

    /**
     * Gets the value of the tm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTM() {
        return tm;
    }

    /**
     * Sets the value of the tm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTM(BigDecimal value) {
        this.tm = value;
    }

    public boolean isSetTM() {
        return (this.tm!= null);
    }

    /**
     * Gets the value of the q property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQ() {
        return q;
    }

    /**
     * Sets the value of the q property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQ(String value) {
        this.q = value;
    }

    public boolean isSetQ() {
        return (this.q!= null);
    }

    /**
     * Gets the value of the param property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the param property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPARAM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GSP.PARAM }
     * 
     * 
     */
    public List<GSP.PARAM> getPARAM() {
        if (param == null) {
            param = new ArrayList<GSP.PARAM>();
        }
        return this.param;
    }

    public boolean isSetPARAM() {
        return ((this.param!= null)&&(!this.param.isEmpty()));
    }

    public void unsetPARAM() {
        this.param = null;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link GSP.Context }
     *     
     */
    public GSP.Context getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link GSP.Context }
     *     
     */
    public void setContext(GSP.Context value) {
        this.context = value;
    }

    public boolean isSetContext() {
        return (this.context!= null);
    }

    /**
     * Gets the value of the res property.
     * 
     * @return
     *     possible object is
     *     {@link GSP.RES }
     *     
     */
    public GSP.RES getRES() {
        return res;
    }

    /**
     * Sets the value of the res property.
     * 
     * @param value
     *     allowed object is
     *     {@link GSP.RES }
     *     
     */
    public void setRES(GSP.RES value) {
        this.res = value;
    }

    public boolean isSetRES() {
        return (this.res!= null);
    }

    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVER() {
        return ver;
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVER(BigDecimal value) {
        this.ver = value;
    }

    public boolean isSetVER() {
        return (this.ver!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title"
    })
    public static class Context
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected String title;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        public boolean isSetTitle() {
            return (this.title!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="original_value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="url_escaped_value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="js_escaped_value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PARAM
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "value")
        protected String value;
        @XmlAttribute(name = "original_value")
        protected String originalValue;
        @XmlAttribute(name = "url_escaped_value")
        protected String urlEscapedValue;
        @XmlAttribute(name = "js_escaped_value")
        protected String jsEscapedValue;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        public boolean isSetName() {
            return (this.name!= null);
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        public boolean isSetValue() {
            return (this.value!= null);
        }

        /**
         * Gets the value of the originalValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginalValue() {
            return originalValue;
        }

        /**
         * Sets the value of the originalValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginalValue(String value) {
            this.originalValue = value;
        }

        public boolean isSetOriginalValue() {
            return (this.originalValue!= null);
        }

        /**
         * Gets the value of the urlEscapedValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrlEscapedValue() {
            return urlEscapedValue;
        }

        /**
         * Sets the value of the urlEscapedValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrlEscapedValue(String value) {
            this.urlEscapedValue = value;
        }

        public boolean isSetUrlEscapedValue() {
            return (this.urlEscapedValue!= null);
        }

        /**
         * Gets the value of the jsEscapedValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJsEscapedValue() {
            return jsEscapedValue;
        }

        /**
         * Sets the value of the jsEscapedValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJsEscapedValue(String value) {
            this.jsEscapedValue = value;
        }

        public boolean isSetJsEscapedValue() {
            return (this.jsEscapedValue!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="M" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="NB">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NU" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RG" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="START" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="SIZE" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="R" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="U" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="T" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RK" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="S" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LANG" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PageMap">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DataObject" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Attribute" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="HAS">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="L" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="C">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="SZ" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="CID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="RT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RHS_COLUMN">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RG">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="START" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="SIZE" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="SN" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="EN" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "m",
        "nb",
        "rg",
        "r",
        "rhscolumn"
    })
    public static class RES
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "M")
        protected int m;
        @XmlElement(name = "NB", required = true)
        protected GSP.RES.NB nb;
        @XmlElement(name = "RG", required = true)
        protected List<GSP.RES.RG> rg;
        @XmlElement(name = "R", required = true)
        protected List<GSP.RES.R> r;
        @XmlElement(name = "RHS_COLUMN", required = true)
        protected GSP.RES.RHSCOLUMN rhscolumn;
        @XmlAttribute(name = "SN")
        protected Integer sn;
        @XmlAttribute(name = "EN")
        protected Integer en;

        /**
         * Gets the value of the m property.
         * 
         */
        public int getM() {
            return m;
        }

        /**
         * Sets the value of the m property.
         * 
         */
        public void setM(int value) {
            this.m = value;
        }

        public boolean isSetM() {
            return true;
        }

        /**
         * Gets the value of the nb property.
         * 
         * @return
         *     possible object is
         *     {@link GSP.RES.NB }
         *     
         */
        public GSP.RES.NB getNB() {
            return nb;
        }

        /**
         * Sets the value of the nb property.
         * 
         * @param value
         *     allowed object is
         *     {@link GSP.RES.NB }
         *     
         */
        public void setNB(GSP.RES.NB value) {
            this.nb = value;
        }

        public boolean isSetNB() {
            return (this.nb!= null);
        }

        /**
         * Gets the value of the rg property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rg property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRG().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GSP.RES.RG }
         * 
         * 
         */
        public List<GSP.RES.RG> getRG() {
            if (rg == null) {
                rg = new ArrayList<GSP.RES.RG>();
            }
            return this.rg;
        }

        public boolean isSetRG() {
            return ((this.rg!= null)&&(!this.rg.isEmpty()));
        }

        public void unsetRG() {
            this.rg = null;
        }

        /**
         * Gets the value of the r property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the r property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getR().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GSP.RES.R }
         * 
         * 
         */
        public List<GSP.RES.R> getR() {
            if (r == null) {
                r = new ArrayList<GSP.RES.R>();
            }
            return this.r;
        }

        public boolean isSetR() {
            return ((this.r!= null)&&(!this.r.isEmpty()));
        }

        public void unsetR() {
            this.r = null;
        }

        /**
         * Gets the value of the rhscolumn property.
         * 
         * @return
         *     possible object is
         *     {@link GSP.RES.RHSCOLUMN }
         *     
         */
        public GSP.RES.RHSCOLUMN getRHSCOLUMN() {
            return rhscolumn;
        }

        /**
         * Sets the value of the rhscolumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link GSP.RES.RHSCOLUMN }
         *     
         */
        public void setRHSCOLUMN(GSP.RES.RHSCOLUMN value) {
            this.rhscolumn = value;
        }

        public boolean isSetRHSCOLUMN() {
            return (this.rhscolumn!= null);
        }

        /**
         * Gets the value of the sn property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getSN() {
            return sn;
        }

        /**
         * Sets the value of the sn property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSN(int value) {
            this.sn = value;
        }

        public boolean isSetSN() {
            return (this.sn!= null);
        }

        public void unsetSN() {
            this.sn = null;
        }

        /**
         * Gets the value of the en property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getEN() {
            return en;
        }

        /**
         * Sets the value of the en property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setEN(int value) {
            this.en = value;
        }

        public boolean isSetEN() {
            return (this.en!= null);
        }

        public void unsetEN() {
            this.en = null;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NU" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nu"
        })
        public static class NB
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "NU", required = true)
            protected String nu;

            /**
             * Gets the value of the nu property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNU() {
                return nu;
            }

            /**
             * Sets the value of the nu property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNU(String value) {
                this.nu = value;
            }

            public boolean isSetNU() {
                return (this.nu!= null);
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="U" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="T" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RK" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="S" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LANG" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PageMap">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DataObject" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Attribute" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="HAS">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="L" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="C">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="SZ" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="CID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="RT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "u",
            "ue",
            "t",
            "rk",
            "s",
            "lang",
            "label",
            "pageMap",
            "has"
        })
        public static class R
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "U", required = true)
            protected String u;
            @XmlElement(name = "UE", required = true)
            protected String ue;
            @XmlElement(name = "T", required = true)
            protected String t;
            @XmlElement(name = "RK")
            protected int rk;
            @XmlElement(name = "S", required = true)
            protected String s;
            @XmlElement(name = "LANG", required = true)
            protected String lang;
            @XmlElement(name = "Label", required = true)
            protected String label;
            @XmlElement(name = "PageMap", required = true)
            protected GSP.RES.R.PageMap pageMap;
            @XmlElement(name = "HAS", required = true)
            protected GSP.RES.R.HAS has;
            @XmlAttribute(name = "N")
            protected Integer n;

            /**
             * Gets the value of the u property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getU() {
                return u;
            }

            /**
             * Sets the value of the u property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setU(String value) {
                this.u = value;
            }

            public boolean isSetU() {
                return (this.u!= null);
            }

            /**
             * Gets the value of the ue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUE() {
                return ue;
            }

            /**
             * Sets the value of the ue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUE(String value) {
                this.ue = value;
            }

            public boolean isSetUE() {
                return (this.ue!= null);
            }

            /**
             * Gets the value of the t property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getT() {
                return t;
            }

            /**
             * Sets the value of the t property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setT(String value) {
                this.t = value;
            }

            public boolean isSetT() {
                return (this.t!= null);
            }

            /**
             * Gets the value of the rk property.
             * 
             */
            public int getRK() {
                return rk;
            }

            /**
             * Sets the value of the rk property.
             * 
             */
            public void setRK(int value) {
                this.rk = value;
            }

            public boolean isSetRK() {
                return true;
            }

            /**
             * Gets the value of the s property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getS() {
                return s;
            }

            /**
             * Sets the value of the s property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setS(String value) {
                this.s = value;
            }

            public boolean isSetS() {
                return (this.s!= null);
            }

            /**
             * Gets the value of the lang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLANG() {
                return lang;
            }

            /**
             * Sets the value of the lang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLANG(String value) {
                this.lang = value;
            }

            public boolean isSetLANG() {
                return (this.lang!= null);
            }

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

            public boolean isSetLabel() {
                return (this.label!= null);
            }

            /**
             * Gets the value of the pageMap property.
             * 
             * @return
             *     possible object is
             *     {@link GSP.RES.R.PageMap }
             *     
             */
            public GSP.RES.R.PageMap getPageMap() {
                return pageMap;
            }

            /**
             * Sets the value of the pageMap property.
             * 
             * @param value
             *     allowed object is
             *     {@link GSP.RES.R.PageMap }
             *     
             */
            public void setPageMap(GSP.RES.R.PageMap value) {
                this.pageMap = value;
            }

            public boolean isSetPageMap() {
                return (this.pageMap!= null);
            }

            /**
             * Gets the value of the has property.
             * 
             * @return
             *     possible object is
             *     {@link GSP.RES.R.HAS }
             *     
             */
            public GSP.RES.R.HAS getHAS() {
                return has;
            }

            /**
             * Sets the value of the has property.
             * 
             * @param value
             *     allowed object is
             *     {@link GSP.RES.R.HAS }
             *     
             */
            public void setHAS(GSP.RES.R.HAS value) {
                this.has = value;
            }

            public boolean isSetHAS() {
                return (this.has!= null);
            }

            /**
             * Gets the value of the n property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getN() {
                return n;
            }

            /**
             * Sets the value of the n property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setN(int value) {
                this.n = value;
            }

            public boolean isSetN() {
                return (this.n!= null);
            }

            public void unsetN() {
                this.n = null;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="L" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="C">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="SZ" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="CID" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="RT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "l",
                "c",
                "rt"
            })
            public static class HAS
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(name = "L", required = true)
                protected String l;
                @XmlElement(name = "C", required = true)
                protected GSP.RES.R.HAS.C c;
                @XmlElement(name = "RT", required = true)
                protected String rt;

                /**
                 * Gets the value of the l property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getL() {
                    return l;
                }

                /**
                 * Sets the value of the l property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setL(String value) {
                    this.l = value;
                }

                public boolean isSetL() {
                    return (this.l!= null);
                }

                /**
                 * Gets the value of the c property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GSP.RES.R.HAS.C }
                 *     
                 */
                public GSP.RES.R.HAS.C getC() {
                    return c;
                }

                /**
                 * Sets the value of the c property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GSP.RES.R.HAS.C }
                 *     
                 */
                public void setC(GSP.RES.R.HAS.C value) {
                    this.c = value;
                }

                public boolean isSetC() {
                    return (this.c!= null);
                }

                /**
                 * Gets the value of the rt property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRT() {
                    return rt;
                }

                /**
                 * Sets the value of the rt property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRT(String value) {
                    this.rt = value;
                }

                public boolean isSetRT() {
                    return (this.rt!= null);
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="SZ" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="CID" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class C
                    implements Serializable
                {

                    private final static long serialVersionUID = 1L;
                    @XmlAttribute(name = "SZ")
                    protected String sz;
                    @XmlAttribute(name = "CID")
                    protected String cid;

                    /**
                     * Gets the value of the sz property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSZ() {
                        return sz;
                    }

                    /**
                     * Sets the value of the sz property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSZ(String value) {
                        this.sz = value;
                    }

                    public boolean isSetSZ() {
                        return (this.sz!= null);
                    }

                    /**
                     * Gets the value of the cid property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCID() {
                        return cid;
                    }

                    /**
                     * Sets the value of the cid property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCID(String value) {
                        this.cid = value;
                    }

                    public boolean isSetCID() {
                        return (this.cid!= null);
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DataObject" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Attribute" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "dataObject"
            })
            public static class PageMap
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(name = "DataObject", required = true)
                protected List<GSP.RES.R.PageMap.DataObject> dataObject;

                /**
                 * Gets the value of the dataObject property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the dataObject property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDataObject().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link GSP.RES.R.PageMap.DataObject }
                 * 
                 * 
                 */
                public List<GSP.RES.R.PageMap.DataObject> getDataObject() {
                    if (dataObject == null) {
                        dataObject = new ArrayList<GSP.RES.R.PageMap.DataObject>();
                    }
                    return this.dataObject;
                }

                public boolean isSetDataObject() {
                    return ((this.dataObject!= null)&&(!this.dataObject.isEmpty()));
                }

                public void unsetDataObject() {
                    this.dataObject = null;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Attribute" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "attribute"
                })
                public static class DataObject
                    implements Serializable
                {

                    private final static long serialVersionUID = 1L;
                    @XmlElement(name = "Attribute", required = true)
                    protected List<GSP.RES.R.PageMap.DataObject.Attribute> attribute;
                    @XmlAttribute(name = "type")
                    protected String type;

                    /**
                     * Gets the value of the attribute property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the attribute property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getAttribute().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link GSP.RES.R.PageMap.DataObject.Attribute }
                     * 
                     * 
                     */
                    public List<GSP.RES.R.PageMap.DataObject.Attribute> getAttribute() {
                        if (attribute == null) {
                            attribute = new ArrayList<GSP.RES.R.PageMap.DataObject.Attribute>();
                        }
                        return this.attribute;
                    }

                    public boolean isSetAttribute() {
                        return ((this.attribute!= null)&&(!this.attribute.isEmpty()));
                    }

                    public void unsetAttribute() {
                        this.attribute = null;
                    }

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                    public boolean isSetType() {
                        return (this.type!= null);
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Attribute
                        implements Serializable
                    {

                        private final static long serialVersionUID = 1L;
                        @XmlAttribute(name = "name")
                        protected String name;
                        @XmlAttribute(name = "value")
                        protected String value;

                        /**
                         * Gets the value of the name property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                        public boolean isSetName() {
                            return (this.name!= null);
                        }

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        public boolean isSetValue() {
                            return (this.value!= null);
                        }

                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="START" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="SIZE" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class RG
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlAttribute(name = "START")
            protected Integer start;
            @XmlAttribute(name = "SIZE")
            protected Integer size;

            /**
             * Gets the value of the start property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getSTART() {
                return start;
            }

            /**
             * Sets the value of the start property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setSTART(int value) {
                this.start = value;
            }

            public boolean isSetSTART() {
                return (this.start!= null);
            }

            public void unsetSTART() {
                this.start = null;
            }

            /**
             * Gets the value of the size property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getSIZE() {
                return size;
            }

            /**
             * Sets the value of the size property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setSIZE(int value) {
                this.size = value;
            }

            public boolean isSetSIZE() {
                return (this.size!= null);
            }

            public void unsetSIZE() {
                this.size = null;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RG">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="START" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="SIZE" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rg"
        })
        public static class RHSCOLUMN
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "RG", required = true)
            protected GSP.RES.RHSCOLUMN.RG rg;

            /**
             * Gets the value of the rg property.
             * 
             * @return
             *     possible object is
             *     {@link GSP.RES.RHSCOLUMN.RG }
             *     
             */
            public GSP.RES.RHSCOLUMN.RG getRG() {
                return rg;
            }

            /**
             * Sets the value of the rg property.
             * 
             * @param value
             *     allowed object is
             *     {@link GSP.RES.RHSCOLUMN.RG }
             *     
             */
            public void setRG(GSP.RES.RHSCOLUMN.RG value) {
                this.rg = value;
            }

            public boolean isSetRG() {
                return (this.rg!= null);
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="START" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="SIZE" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class RG
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlAttribute(name = "START")
                protected Integer start;
                @XmlAttribute(name = "SIZE")
                protected Integer size;

                /**
                 * Gets the value of the start property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getSTART() {
                    return start;
                }

                /**
                 * Sets the value of the start property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setSTART(int value) {
                    this.start = value;
                }

                public boolean isSetSTART() {
                    return (this.start!= null);
                }

                public void unsetSTART() {
                    this.start = null;
                }

                /**
                 * Gets the value of the size property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getSIZE() {
                    return size;
                }

                /**
                 * Sets the value of the size property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setSIZE(int value) {
                    this.size = value;
                }

                public boolean isSetSIZE() {
                    return (this.size!= null);
                }

                public void unsetSIZE() {
                    this.size = null;
                }

            }

        }

    }

}
