//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LifeDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LifeDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType" minOccurs="0"/>
 *         &lt;element name="TimeLine" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}TimeLineType" minOccurs="0"/>
 *         &lt;element name="Dealers" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}DealersType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LifeDataType", propOrder = {
    "status",
    "timeLine",
    "dealers"
})
public class LifeDataType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Status", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected CodeType status;
    @XmlElement(name = "TimeLine", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected TimeLineType timeLine;
    @XmlElement(name = "Dealers", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected DealersType dealers;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setStatus(CodeType value) {
        this.status = value;
    }

    public boolean isSetStatus() {
        return (this.status!= null);
    }

    /**
     * Gets the value of the timeLine property.
     * 
     * @return
     *     possible object is
     *     {@link TimeLineType }
     *     
     */
    public TimeLineType getTimeLine() {
        return timeLine;
    }

    /**
     * Sets the value of the timeLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeLineType }
     *     
     */
    public void setTimeLine(TimeLineType value) {
        this.timeLine = value;
    }

    public boolean isSetTimeLine() {
        return (this.timeLine!= null);
    }

    /**
     * Gets the value of the dealers property.
     * 
     * @return
     *     possible object is
     *     {@link DealersType }
     *     
     */
    public DealersType getDealers() {
        return dealers;
    }

    /**
     * Sets the value of the dealers property.
     * 
     * @param value
     *     allowed object is
     *     {@link DealersType }
     *     
     */
    public void setDealers(DealersType value) {
        this.dealers = value;
    }

    public boolean isSetDealers() {
        return (this.dealers!= null);
    }

}
