//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.autodata.vw.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetEquipmentResponse_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/services/DataService/VehicleLifecycleService/V1", "GetEquipmentResponse");
    private final static QName _Vehicle_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/DD/Vehicle", "Vehicle");
    private final static QName _GetEquipment_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/services/DataService/VehicleLifecycleService/V1", "GetEquipment");
    private final static QName _Confirmation_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", "Confirmation");
    private final static QName _AliveTestAcknowledgement_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", "AliveTestAcknowledgement");
    private final static QName _FaultBasic_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", "FaultBasic");
    private final static QName _VehicleRef_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/DD/Vehicle", "VehicleRef");
    private final static QName _AcknowledgeAliveTest_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/services/DataService/VehicleLifecycleService/V1", "AcknowledgeAliveTest");
    private final static QName _DealerRef_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1", "DealerRef");
    private final static QName _VehicleIdentifier_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/services/DataService/VehicleLifecycleService/V1", "VehicleIdentifier");
    private final static QName _ProcessAliveTest_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/services/DataService/VehicleLifecycleService/V1", "ProcessAliveTest");
    private final static QName _Fault_QNAME = new QName("http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", "Fault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.autodata.vw.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GSP }
     * 
     */
    public GSP createGSP() {
        return new GSP();
    }

    /**
     * Create an instance of {@link Offers }
     * 
     */
    public Offers createOffers() {
        return new Offers();
    }

    /**
     * Create an instance of {@link Offers.Daa }
     * 
     */
    public Offers.Daa createOffersDaa() {
        return new Offers.Daa();
    }

    /**
     * Create an instance of {@link Offers.Daa.Deal }
     * 
     */
    public Offers.Daa.Deal createOffersDaaDeal() {
        return new Offers.Daa.Deal();
    }

    /**
     * Create an instance of {@link Offers.Regional }
     * 
     */
    public Offers.Regional createOffersRegional() {
        return new Offers.Regional();
    }

    /**
     * Create an instance of {@link Offers.Regional.Deal }
     * 
     */
    public Offers.Regional.Deal createOffersRegionalDeal() {
        return new Offers.Regional.Deal();
    }

    /**
     * Create an instance of {@link Offers.National }
     * 
     */
    public Offers.National createOffersNational() {
        return new Offers.National();
    }

    /**
     * Create an instance of {@link Offers.National.Deal }
     * 
     */
    public Offers.National.Deal createOffersNationalDeal() {
        return new Offers.National.Deal();
    }

    /**
     * Create an instance of {@link GSP.RES }
     * 
     */
    public GSP.RES createGSPRES() {
        return new GSP.RES();
    }

    /**
     * Create an instance of {@link GSP.RES.RHSCOLUMN }
     * 
     */
    public GSP.RES.RHSCOLUMN createGSPRESRHSCOLUMN() {
        return new GSP.RES.RHSCOLUMN();
    }

    /**
     * Create an instance of {@link GSP.RES.R }
     * 
     */
    public GSP.RES.R createGSPRESR() {
        return new GSP.RES.R();
    }

    /**
     * Create an instance of {@link GSP.RES.R.HAS }
     * 
     */
    public GSP.RES.R.HAS createGSPRESRHAS() {
        return new GSP.RES.R.HAS();
    }

    /**
     * Create an instance of {@link GSP.RES.R.PageMap }
     * 
     */
    public GSP.RES.R.PageMap createGSPRESRPageMap() {
        return new GSP.RES.R.PageMap();
    }

    /**
     * Create an instance of {@link GSP.RES.R.PageMap.DataObject }
     * 
     */
    public GSP.RES.R.PageMap.DataObject createGSPRESRPageMapDataObject() {
        return new GSP.RES.R.PageMap.DataObject();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link CountryCodeType }
     * 
     */
    public CountryCodeType createCountryCodeType() {
        return new CountryCodeType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link AliveTestAcknowledgementType }
     * 
     */
    public AliveTestAcknowledgementType createAliveTestAcknowledgementType() {
        return new AliveTestAcknowledgementType();
    }

    /**
     * Create an instance of {@link ConfirmationType }
     * 
     */
    public ConfirmationType createConfirmationType() {
        return new ConfirmationType();
    }

    /**
     * Create an instance of {@link FaultBasicType }
     * 
     */
    public FaultBasicType createFaultBasicType() {
        return new FaultBasicType();
    }

    /**
     * Create an instance of {@link FaultType }
     * 
     */
    public FaultType createFaultType() {
        return new FaultType();
    }

    /**
     * Create an instance of {@link FaultSystemDetailType }
     * 
     */
    public FaultSystemDetailType createFaultSystemDetailType() {
        return new FaultSystemDetailType();
    }

    /**
     * Create an instance of {@link CodeParamType }
     * 
     */
    public CodeParamType createCodeParamType() {
        return new CodeParamType();
    }

    /**
     * Create an instance of {@link FaultCodeDetailType }
     * 
     */
    public FaultCodeDetailType createFaultCodeDetailType() {
        return new FaultCodeDetailType();
    }

    /**
     * Create an instance of {@link ServiceInfoType }
     * 
     */
    public ServiceInfoType createServiceInfoType() {
        return new ServiceInfoType();
    }

    /**
     * Create an instance of {@link ServiceProviderType }
     * 
     */
    public ServiceProviderType createServiceProviderType() {
        return new ServiceProviderType();
    }

    /**
     * Create an instance of {@link SystemParamType }
     * 
     */
    public SystemParamType createSystemParamType() {
        return new SystemParamType();
    }

    /**
     * Create an instance of {@link GetEquipmentType }
     * 
     */
    public GetEquipmentType createGetEquipmentType() {
        return new GetEquipmentType();
    }

    /**
     * Create an instance of {@link GetEquipmentResponseType }
     * 
     */
    public GetEquipmentResponseType createGetEquipmentResponseType() {
        return new GetEquipmentResponseType();
    }

    /**
     * Create an instance of {@link AcknowledgeAliveTestType }
     * 
     */
    public AcknowledgeAliveTestType createAcknowledgeAliveTestType() {
        return new AcknowledgeAliveTestType();
    }

    /**
     * Create an instance of {@link VehicleReference }
     * 
     */
    public VehicleReference createVehicleReference() {
        return new VehicleReference();
    }

    /**
     * Create an instance of {@link GetEntryResponse }
     * 
     */
    public GetEntryResponse createGetEntryResponse() {
        return new GetEntryResponse();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link GetEntry }
     * 
     */
    public GetEntry createGetEntry() {
        return new GetEntry();
    }

    /**
     * Create an instance of {@link VehicleIdentifierType }
     * 
     */
    public VehicleIdentifierType createVehicleIdentifierType() {
        return new VehicleIdentifierType();
    }

    /**
     * Create an instance of {@link ProcessAliveTestType }
     * 
     */
    public ProcessAliveTestType createProcessAliveTestType() {
        return new ProcessAliveTestType();
    }

    /**
     * Create an instance of {@link EquipmentDescriptionType }
     * 
     */
    public EquipmentDescriptionType createEquipmentDescriptionType() {
        return new EquipmentDescriptionType();
    }

    /**
     * Create an instance of {@link EnginesType }
     * 
     */
    public EnginesType createEnginesType() {
        return new EnginesType();
    }

    /**
     * Create an instance of {@link DealerType }
     * 
     */
    public DealerType createDealerType() {
        return new DealerType();
    }

    /**
     * Create an instance of {@link TechnicalDataType }
     * 
     */
    public TechnicalDataType createTechnicalDataType() {
        return new TechnicalDataType();
    }

    /**
     * Create an instance of {@link ProductionDateType }
     * 
     */
    public ProductionDateType createProductionDateType() {
        return new ProductionDateType();
    }

    /**
     * Create an instance of {@link DeliveryDateType }
     * 
     */
    public DeliveryDateType createDeliveryDateType() {
        return new DeliveryDateType();
    }

    /**
     * Create an instance of {@link TransmissionType }
     * 
     */
    public TransmissionType createTransmissionType() {
        return new TransmissionType();
    }

    /**
     * Create an instance of {@link ManufacturerType }
     * 
     */
    public ManufacturerType createManufacturerType() {
        return new ManufacturerType();
    }

    /**
     * Create an instance of {@link ColorsType }
     * 
     */
    public ColorsType createColorsType() {
        return new ColorsType();
    }

    /**
     * Create an instance of {@link EquipmentOptionsType }
     * 
     */
    public EquipmentOptionsType createEquipmentOptionsType() {
        return new EquipmentOptionsType();
    }

    /**
     * Create an instance of {@link TransmissionsType }
     * 
     */
    public TransmissionsType createTransmissionsType() {
        return new TransmissionsType();
    }

    /**
     * Create an instance of {@link TimeLineType }
     * 
     */
    public TimeLineType createTimeLineType() {
        return new TimeLineType();
    }

    /**
     * Create an instance of {@link EquipmentsType }
     * 
     */
    public EquipmentsType createEquipmentsType() {
        return new EquipmentsType();
    }

    /**
     * Create an instance of {@link EngineType }
     * 
     */
    public EngineType createEngineType() {
        return new EngineType();
    }

    /**
     * Create an instance of {@link EquipmentType }
     * 
     */
    public EquipmentType createEquipmentType() {
        return new EquipmentType();
    }

    /**
     * Create an instance of {@link ModelType }
     * 
     */
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link EquipmentOptionType }
     * 
     */
    public EquipmentOptionType createEquipmentOptionType() {
        return new EquipmentOptionType();
    }

    /**
     * Create an instance of {@link EquipmentDescriptionsType }
     * 
     */
    public EquipmentDescriptionsType createEquipmentDescriptionsType() {
        return new EquipmentDescriptionsType();
    }

    /**
     * Create an instance of {@link ADIType }
     * 
     */
    public ADIType createADIType() {
        return new ADIType();
    }

    /**
     * Create an instance of {@link InteriorsType }
     * 
     */
    public InteriorsType createInteriorsType() {
        return new InteriorsType();
    }

    /**
     * Create an instance of {@link LifeDataType }
     * 
     */
    public LifeDataType createLifeDataType() {
        return new LifeDataType();
    }

    /**
     * Create an instance of {@link DealersType }
     * 
     */
    public DealersType createDealersType() {
        return new DealersType();
    }

    /**
     * Create an instance of {@link ModelCodesType }
     * 
     */
    public ModelCodesType createModelCodesType() {
        return new ModelCodesType();
    }

    /**
     * Create an instance of {@link PartnerIdentifierType }
     * 
     */
    public PartnerIdentifierType createPartnerIdentifierType() {
        return new PartnerIdentifierType();
    }

    /**
     * Create an instance of {@link WholesalerIdentifierType }
     * 
     */
    public WholesalerIdentifierType createWholesalerIdentifierType() {
        return new WholesalerIdentifierType();
    }

    /**
     * Create an instance of {@link PartnerKeyType }
     * 
     */
    public PartnerKeyType createPartnerKeyType() {
        return new PartnerKeyType();
    }

    /**
     * Create an instance of {@link DealerIdentifierType }
     * 
     */
    public DealerIdentifierType createDealerIdentifierType() {
        return new DealerIdentifierType();
    }

    /**
     * Create an instance of {@link GSP.PARAM }
     * 
     */
    public GSP.PARAM createGSPPARAM() {
        return new GSP.PARAM();
    }

    /**
     * Create an instance of {@link GSP.Context }
     * 
     */
    public GSP.Context createGSPContext() {
        return new GSP.Context();
    }

    /**
     * Create an instance of {@link Offers.Daa.Deal.OfferTypes }
     * 
     */
    public Offers.Daa.Deal.OfferTypes createOffersDaaDealOfferTypes() {
        return new Offers.Daa.Deal.OfferTypes();
    }

    /**
     * Create an instance of {@link Offers.Daa.Deal.Car }
     * 
     */
    public Offers.Daa.Deal.Car createOffersDaaDealCar() {
        return new Offers.Daa.Deal.Car();
    }

    /**
     * Create an instance of {@link Offers.Regional.Deal.OfferTypes }
     * 
     */
    public Offers.Regional.Deal.OfferTypes createOffersRegionalDealOfferTypes() {
        return new Offers.Regional.Deal.OfferTypes();
    }

    /**
     * Create an instance of {@link Offers.Regional.Deal.Car }
     * 
     */
    public Offers.Regional.Deal.Car createOffersRegionalDealCar() {
        return new Offers.Regional.Deal.Car();
    }

    /**
     * Create an instance of {@link Offers.National.Deal.OfferTypes }
     * 
     */
    public Offers.National.Deal.OfferTypes createOffersNationalDealOfferTypes() {
        return new Offers.National.Deal.OfferTypes();
    }

    /**
     * Create an instance of {@link Offers.National.Deal.Car }
     * 
     */
    public Offers.National.Deal.Car createOffersNationalDealCar() {
        return new Offers.National.Deal.Car();
    }

    /**
     * Create an instance of {@link Offers.National.Deal.CustomImage }
     * 
     */
    public Offers.National.Deal.CustomImage createOffersNationalDealCustomImage() {
        return new Offers.National.Deal.CustomImage();
    }

    /**
     * Create an instance of {@link GSP.RES.NB }
     * 
     */
    public GSP.RES.NB createGSPRESNB() {
        return new GSP.RES.NB();
    }

    /**
     * Create an instance of {@link GSP.RES.RG }
     * 
     */
    public GSP.RES.RG createGSPRESRG() {
        return new GSP.RES.RG();
    }

    /**
     * Create an instance of {@link GSP.RES.RHSCOLUMN.RG }
     * 
     */
    public GSP.RES.RHSCOLUMN.RG createGSPRESRHSCOLUMNRG() {
        return new GSP.RES.RHSCOLUMN.RG();
    }

    /**
     * Create an instance of {@link GSP.RES.R.HAS.C }
     * 
     */
    public GSP.RES.R.HAS.C createGSPRESRHASC() {
        return new GSP.RES.R.HAS.C();
    }

    /**
     * Create an instance of {@link GSP.RES.R.PageMap.DataObject.Attribute }
     * 
     */
    public GSP.RES.R.PageMap.DataObject.Attribute createGSPRESRPageMapDataObjectAttribute() {
        return new GSP.RES.R.PageMap.DataObject.Attribute();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEquipmentResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/services/DataService/VehicleLifecycleService/V1", name = "GetEquipmentResponse")
    public JAXBElement<GetEquipmentResponseType> createGetEquipmentResponse(GetEquipmentResponseType value) {
        return new JAXBElement<GetEquipmentResponseType>(_GetEquipmentResponse_QNAME, GetEquipmentResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VehicleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle", name = "Vehicle")
    public JAXBElement<VehicleType> createVehicle(VehicleType value) {
        return new JAXBElement<VehicleType>(_Vehicle_QNAME, VehicleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEquipmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/services/DataService/VehicleLifecycleService/V1", name = "GetEquipment")
    public JAXBElement<GetEquipmentType> createGetEquipment(GetEquipmentType value) {
        return new JAXBElement<GetEquipmentType>(_GetEquipment_QNAME, GetEquipmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", name = "Confirmation")
    public JAXBElement<ConfirmationType> createConfirmation(ConfirmationType value) {
        return new JAXBElement<ConfirmationType>(_Confirmation_QNAME, ConfirmationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AliveTestAcknowledgementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", name = "AliveTestAcknowledgement")
    public JAXBElement<AliveTestAcknowledgementType> createAliveTestAcknowledgement(AliveTestAcknowledgementType value) {
        return new JAXBElement<AliveTestAcknowledgementType>(_AliveTestAcknowledgement_QNAME, AliveTestAcknowledgementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultBasicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", name = "FaultBasic")
    public JAXBElement<FaultBasicType> createFaultBasic(FaultBasicType value) {
        return new JAXBElement<FaultBasicType>(_FaultBasic_QNAME, FaultBasicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VehicleIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle", name = "VehicleRef")
    public JAXBElement<VehicleIdentifierType> createVehicleRef(VehicleIdentifierType value) {
        return new JAXBElement<VehicleIdentifierType>(_VehicleRef_QNAME, VehicleIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgeAliveTestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/services/DataService/VehicleLifecycleService/V1", name = "AcknowledgeAliveTest")
    public JAXBElement<AcknowledgeAliveTestType> createAcknowledgeAliveTest(AcknowledgeAliveTestType value) {
        return new JAXBElement<AcknowledgeAliveTestType>(_AcknowledgeAliveTest_QNAME, AcknowledgeAliveTestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartnerIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1", name = "DealerRef")
    public JAXBElement<PartnerIdentifierType> createDealerRef(PartnerIdentifierType value) {
        return new JAXBElement<PartnerIdentifierType>(_DealerRef_QNAME, PartnerIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VehicleReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/services/DataService/VehicleLifecycleService/V1", name = "VehicleIdentifier")
    public JAXBElement<VehicleReference> createVehicleIdentifier(VehicleReference value) {
        return new JAXBElement<VehicleReference>(_VehicleIdentifier_QNAME, VehicleReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessAliveTestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/services/DataService/VehicleLifecycleService/V1", name = "ProcessAliveTest")
    public JAXBElement<ProcessAliveTestType> createProcessAliveTest(ProcessAliveTestType value) {
        return new JAXBElement<ProcessAliveTestType>(_ProcessAliveTest_QNAME, ProcessAliveTestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", name = "Fault")
    public JAXBElement<FaultType> createFault(FaultType value) {
        return new JAXBElement<FaultType>(_Fault_QNAME, FaultType.class, null, value);
    }

}
