//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
package net.autodata.vw.model;
