//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartnerIdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartnerIdentifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DealerIdentifier" type="{http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1}DealerIdentifierType" minOccurs="0"/>
 *         &lt;element name="WholesalerIdentifier" type="{http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1}WholesalerIdentifierType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerIdentifierType", namespace = "http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1", propOrder = {
    "dealerIdentifier",
    "wholesalerIdentifier"
})
public class PartnerIdentifierType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "DealerIdentifier", namespace = "http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1")
    protected DealerIdentifierType dealerIdentifier;
    @XmlElement(name = "WholesalerIdentifier", namespace = "http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1")
    protected WholesalerIdentifierType wholesalerIdentifier;

    /**
     * Gets the value of the dealerIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link DealerIdentifierType }
     *     
     */
    public DealerIdentifierType getDealerIdentifier() {
        return dealerIdentifier;
    }

    /**
     * Sets the value of the dealerIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link DealerIdentifierType }
     *     
     */
    public void setDealerIdentifier(DealerIdentifierType value) {
        this.dealerIdentifier = value;
    }

    public boolean isSetDealerIdentifier() {
        return (this.dealerIdentifier!= null);
    }

    /**
     * Gets the value of the wholesalerIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link WholesalerIdentifierType }
     *     
     */
    public WholesalerIdentifierType getWholesalerIdentifier() {
        return wholesalerIdentifier;
    }

    /**
     * Sets the value of the wholesalerIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link WholesalerIdentifierType }
     *     
     */
    public void setWholesalerIdentifier(WholesalerIdentifierType value) {
        this.wholesalerIdentifier = value;
    }

    public boolean isSetWholesalerIdentifier() {
        return (this.wholesalerIdentifier!= null);
    }

}
