//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PartnerKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartnerKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Country" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CountryCodeType" minOccurs="0"/>
 *         &lt;element name="Brand" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType" minOccurs="0"/>
 *         &lt;element name="PartnerNumber" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerKeyType", namespace = "http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1", propOrder = {
    "country",
    "brand",
    "partnerNumber"
})
public class PartnerKeyType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Country", namespace = "http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1")
    protected CountryCodeType country;
    @XmlElement(name = "Brand", namespace = "http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1")
    protected CodeType brand;
    @XmlElement(name = "PartnerNumber", namespace = "http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String partnerNumber;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeType }
     *     
     */
    public CountryCodeType getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeType }
     *     
     */
    public void setCountry(CountryCodeType value) {
        this.country = value;
    }

    public boolean isSetCountry() {
        return (this.country!= null);
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setBrand(CodeType value) {
        this.brand = value;
    }

    public boolean isSetBrand() {
        return (this.brand!= null);
    }

    /**
     * Gets the value of the partnerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerNumber() {
        return partnerNumber;
    }

    /**
     * Sets the value of the partnerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerNumber(String value) {
        this.partnerNumber = value;
    }

    public boolean isSetPartnerNumber() {
        return (this.partnerNumber!= null);
    }

}
