//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceProviderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceProviderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Hostname" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}NameType"/>
 *         &lt;element name="Name" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}NameType"/>
 *         &lt;element name="Version" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}IdentifierType"/>
 *         &lt;element name="Vendor" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}NameType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceProviderType", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", propOrder = {
    "hostname",
    "name",
    "version",
    "vendor"
})
public class ServiceProviderType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Hostname", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected NameType hostname;
    @XmlElement(name = "Name", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected NameType name;
    @XmlElement(name = "Version", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected IdentifierType version;
    @XmlElement(name = "Vendor", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2")
    protected NameType vendor;

    /**
     * Gets the value of the hostname property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getHostname() {
        return hostname;
    }

    /**
     * Sets the value of the hostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setHostname(NameType value) {
        this.hostname = value;
    }

    public boolean isSetHostname() {
        return (this.hostname!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setName(NameType value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setVersion(IdentifierType value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version!= null);
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setVendor(NameType value) {
        this.vendor = value;
    }

    public boolean isSetVendor() {
        return (this.vendor!= null);
    }

}
