//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SystemParamType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SystemParamType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParamName" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType"/>
 *         &lt;element name="ParamValue" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}String"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemParamType", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", propOrder = {
    "paramName",
    "paramValue"
})
public class SystemParamType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ParamName", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    protected CodeType paramName;
    @XmlElement(name = "ParamValue", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Commons/V2", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String paramValue;

    /**
     * Gets the value of the paramName property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getParamName() {
        return paramName;
    }

    /**
     * Sets the value of the paramName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setParamName(CodeType value) {
        this.paramName = value;
    }

    public boolean isSetParamName() {
        return (this.paramName!= null);
    }

    /**
     * Gets the value of the paramValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * Sets the value of the paramValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamValue(String value) {
        this.paramValue = value;
    }

    public boolean isSetParamValue() {
        return (this.paramValue!= null);
    }

}
