//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TechnicalDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TechnicalDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ADI" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}ADIType" minOccurs="0"/>
 *         &lt;element name="Engines" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}EnginesType" minOccurs="0"/>
 *         &lt;element name="Transmissions" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}TransmissionsType" minOccurs="0"/>
 *         &lt;element name="Equipments" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}EquipmentsType" minOccurs="0"/>
 *         &lt;element name="CountryComposition" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TechnicalDataType", propOrder = {
    "adi",
    "engines",
    "transmissions",
    "equipments",
    "countryComposition"
})
public class TechnicalDataType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ADI", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected ADIType adi;
    @XmlElement(name = "Engines", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected EnginesType engines;
    @XmlElement(name = "Transmissions", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected TransmissionsType transmissions;
    @XmlElement(name = "Equipments", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected EquipmentsType equipments;
    @XmlElement(name = "CountryComposition", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected CodeType countryComposition;

    /**
     * Gets the value of the adi property.
     * 
     * @return
     *     possible object is
     *     {@link ADIType }
     *     
     */
    public ADIType getADI() {
        return adi;
    }

    /**
     * Sets the value of the adi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADIType }
     *     
     */
    public void setADI(ADIType value) {
        this.adi = value;
    }

    public boolean isSetADI() {
        return (this.adi!= null);
    }

    /**
     * Gets the value of the engines property.
     * 
     * @return
     *     possible object is
     *     {@link EnginesType }
     *     
     */
    public EnginesType getEngines() {
        return engines;
    }

    /**
     * Sets the value of the engines property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnginesType }
     *     
     */
    public void setEngines(EnginesType value) {
        this.engines = value;
    }

    public boolean isSetEngines() {
        return (this.engines!= null);
    }

    /**
     * Gets the value of the transmissions property.
     * 
     * @return
     *     possible object is
     *     {@link TransmissionsType }
     *     
     */
    public TransmissionsType getTransmissions() {
        return transmissions;
    }

    /**
     * Sets the value of the transmissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmissionsType }
     *     
     */
    public void setTransmissions(TransmissionsType value) {
        this.transmissions = value;
    }

    public boolean isSetTransmissions() {
        return (this.transmissions!= null);
    }

    /**
     * Gets the value of the equipments property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentsType }
     *     
     */
    public EquipmentsType getEquipments() {
        return equipments;
    }

    /**
     * Sets the value of the equipments property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentsType }
     *     
     */
    public void setEquipments(EquipmentsType value) {
        this.equipments = value;
    }

    public boolean isSetEquipments() {
        return (this.equipments!= null);
    }

    /**
     * Gets the value of the countryComposition property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getCountryComposition() {
        return countryComposition;
    }

    /**
     * Sets the value of the countryComposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setCountryComposition(CodeType value) {
        this.countryComposition = value;
    }

    public boolean isSetCountryComposition() {
        return (this.countryComposition!= null);
    }

}
