//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeLineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductionDate" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}ProductionDateType" minOccurs="0"/>
 *         &lt;element name="DeliveryDate" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}DeliveryDateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeLineType", propOrder = {
    "productionDate",
    "deliveryDate"
})
public class TimeLineType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ProductionDate", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected ProductionDateType productionDate;
    @XmlElement(name = "DeliveryDate", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected DeliveryDateType deliveryDate;

    /**
     * Gets the value of the productionDate property.
     * 
     * @return
     *     possible object is
     *     {@link ProductionDateType }
     *     
     */
    public ProductionDateType getProductionDate() {
        return productionDate;
    }

    /**
     * Sets the value of the productionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductionDateType }
     *     
     */
    public void setProductionDate(ProductionDateType value) {
        this.productionDate = value;
    }

    public boolean isSetProductionDate() {
        return (this.productionDate!= null);
    }

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryDateType }
     *     
     */
    public DeliveryDateType getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryDateType }
     *     
     */
    public void setDeliveryDate(DeliveryDateType value) {
        this.deliveryDate = value;
    }

    public boolean isSetDeliveryDate() {
        return (this.deliveryDate!= null);
    }

}
