//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransmissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransmissionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Kind" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType"/>
 *         &lt;element name="TransmissionCode" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}CodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransmissionType", propOrder = {
    "kind",
    "transmissionCode"
})
public class TransmissionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Kind", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle", required = true)
    protected CodeType kind;
    @XmlElement(name = "TransmissionCode", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected CodeType transmissionCode;

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setKind(CodeType value) {
        this.kind = value;
    }

    public boolean isSetKind() {
        return (this.kind!= null);
    }

    /**
     * Gets the value of the transmissionCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getTransmissionCode() {
        return transmissionCode;
    }

    /**
     * Sets the value of the transmissionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setTransmissionCode(CodeType value) {
        this.transmissionCode = value;
    }

    public boolean isSetTransmissionCode() {
        return (this.transmissionCode!= null);
    }

}
