//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehicleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VehicleIdentifier" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}VehicleIdentifierType" minOccurs="0"/>
 *         &lt;element name="Manufacturer" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}ManufacturerType" minOccurs="0"/>
 *         &lt;element name="Model" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}ModelType" minOccurs="0"/>
 *         &lt;element name="TechnicalData" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}TechnicalDataType" minOccurs="0"/>
 *         &lt;element name="LifeData" type="{http://xmldefs.vwgoa.na.vwg/DD/Vehicle}LifeDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleType", propOrder = {
    "vehicleIdentifier",
    "manufacturer",
    "model",
    "technicalData",
    "lifeData"
})
public class VehicleType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "VehicleIdentifier", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected VehicleIdentifierType vehicleIdentifier;
    @XmlElement(name = "Manufacturer", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected ManufacturerType manufacturer;
    @XmlElement(name = "Model", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected ModelType model;
    @XmlElement(name = "TechnicalData", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected TechnicalDataType technicalData;
    @XmlElement(name = "LifeData", namespace = "http://xmldefs.vwgoa.na.vwg/DD/Vehicle")
    protected LifeDataType lifeData;

    /**
     * Gets the value of the vehicleIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleIdentifierType }
     *     
     */
    public VehicleIdentifierType getVehicleIdentifier() {
        return vehicleIdentifier;
    }

    /**
     * Sets the value of the vehicleIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleIdentifierType }
     *     
     */
    public void setVehicleIdentifier(VehicleIdentifierType value) {
        this.vehicleIdentifier = value;
    }

    public boolean isSetVehicleIdentifier() {
        return (this.vehicleIdentifier!= null);
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link ManufacturerType }
     *     
     */
    public ManufacturerType getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManufacturerType }
     *     
     */
    public void setManufacturer(ManufacturerType value) {
        this.manufacturer = value;
    }

    public boolean isSetManufacturer() {
        return (this.manufacturer!= null);
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link ModelType }
     *     
     */
    public ModelType getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelType }
     *     
     */
    public void setModel(ModelType value) {
        this.model = value;
    }

    public boolean isSetModel() {
        return (this.model!= null);
    }

    /**
     * Gets the value of the technicalData property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalDataType }
     *     
     */
    public TechnicalDataType getTechnicalData() {
        return technicalData;
    }

    /**
     * Sets the value of the technicalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalDataType }
     *     
     */
    public void setTechnicalData(TechnicalDataType value) {
        this.technicalData = value;
    }

    public boolean isSetTechnicalData() {
        return (this.technicalData!= null);
    }

    /**
     * Gets the value of the lifeData property.
     * 
     * @return
     *     possible object is
     *     {@link LifeDataType }
     *     
     */
    public LifeDataType getLifeData() {
        return lifeData;
    }

    /**
     * Sets the value of the lifeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeDataType }
     *     
     */
    public void setLifeData(LifeDataType value) {
        this.lifeData = value;
    }

    public boolean isSetLifeData() {
        return (this.lifeData!= null);
    }

}
