//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 05:18:11 PM IST 
//


package net.autodata.vw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for WholesalerIdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WholesalerIdentifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WholesalerNumber" type="{http://xmldefs.vwgoa.na.vwg/DD/BasicTypes/V2}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WholesalerIdentifierType", namespace = "http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1", propOrder = {
    "wholesalerNumber"
})
public class WholesalerIdentifierType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "WholesalerNumber", namespace = "http://xmldefs.vwgoa.na.vwg/DD/BusinessPartner/Ref/V1")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String wholesalerNumber;

    /**
     * Gets the value of the wholesalerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWholesalerNumber() {
        return wholesalerNumber;
    }

    /**
     * Sets the value of the wholesalerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWholesalerNumber(String value) {
        this.wholesalerNumber = value;
    }

    public boolean isSetWholesalerNumber() {
        return (this.wholesalerNumber!= null);
    }

}
